version: "3.8"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: rodb-postgres-db_1
      APP_PORT: 5432
    
  server:
    image: postgres:17
    user: "5432:5432"
    init: true
