version: "3.7"

services:
  server:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    user:
      - "5432:5432"
    environment:
      APP_HOST: rodb-postgres_1
      APP_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: master
    volumes:
      - /home/umbrel/umbrel/app-data/postgres/data:/var/lib/postgresql/data
