services:
  windows:
    image: dockurr/windows
    container_name: rodb-winsvr2025
    environment:
      VERSION: "2025"
      HOSTNAME: "Dockur-WinSvr25"
      RAM_SIZE: "14G"
      CPU_CORES: "16"
      DISK_SIZE: "500G"
      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - '8006:8006'
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/umbrel/umbrel/app-data/rodb-win2025/data:/storage
    restart: always
    stop_grace_period: 2m